[tool.poetry]
name = "human-vasculature"
version = "0.1.0"
description = ""
authors = ["Maksim_Kalinin <kalinin.ma@digitalsv.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
